name: Deploy HLS to GitHub Pages

on:
  push:
    branches:
      - main

# Grant necessary token permissions for pages and id-token
permissions:
  contents: read        # for checkout
  pages: write          # for Pages deploy
  id-token: write       # for OIDC token

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. (Optional) Build or preprocess files
      # - name: Build HLS artifacts
      #   run: |
      #     ffmpeg ... # your build commands

      # 3. Upload the site as artifact
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .        # include .m3u8, .ts, HTML, .nojekyll

      # 4. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
